### ISSUE TITLE
Design Municipal Page

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#29]
This is a page that will allow a user to explore the submarkets that are within their municipality.  Called "Find a Community" in Chicago site I think we may want to call "Explore".  

**Questions:**
- [x] Name for page (/municipalities)
- [x] Need to decide if this is a full-page map and how it differed from the home page in layout. (not full)
- [x] Only municipalities groupings? (yes)
- [x] Tooltip to include % subregion in muni (no)
- [x] % bar in tooltip? (no)
- [x] What site copy do we want to include on this page?(policy embed)

Very drafty example:
![image](https://user-images.githubusercontent.com/2421382/106795103-aef54780-6627-11eb-9e39-246124fd60d4.png)

**Comment by theryankelly** [comment]
**Switch menu to differentiate**
![image](https://user-images.githubusercontent.com/2421382/106804406-59bf3300-6633-11eb-8b0e-d858a7ba245d.png)

**Comment by theryankelly** [comment]
Was trying to think of another layout that did not conflict with home page and still allowed the user to find their community and submarket within. What about a much more contained map. Still with zoom click options, but one that drives primarily by search? This mockup doesn't currently communicate/display the input or overlay factors for a community/submarkets in a community.

![image](https://user-images.githubusercontent.com/2421382/107440702-0866e600-6b02-11eb-8a51-c63d2e614b82.png)

**Comment by atomtay** [comment]
I really like having a different template than the homepage---I think it'll make it clearer to the user which page does what. The one concern I'm still thinking through, though, is how to connect the geocoder to the bottom lefthand "results" panel. It would work great if the user searches for "Boston" or "Acton," but we don't currently have data identified for individual neighborhoods (if the user searches for "Roxbury" or "Coolidge Corner", or maybe even their particular address). I see two potential solutions to this:

1) Instead of using Mapbox's geocoder, create and use our own search feature limited to the 101 municipalities (like we have for the Zoning Atlas municipality filter)
2) If possible, determine the municipality from the Mapbox search ("Boston" for "Roxbury," "Brookline" for "Coolidge Corner") and return those results.

I'm somewhat more partial to the first option, as it restricts possible inputs to our available outputs. In that case, I'd re-title the page "Municipal Search" to make clear that this is a very particular definition of "community" that we're searching by.

Tagging @Kit-Un as well to see her thoughts

**Comment by atomtay** [comment]
I was able to combine these approaches and use the Mapbox geocoder (#19), filtered to the 101 municipalities in the region:
![Screen Shot 2021-02-10 at 1 31 02 PM](https://user-images.githubusercontent.com/10645500/107554734-592f1b00-6ba4-11eb-9fa4-c1d28a5eaf16.png)

Adding the second half (X% of municipality in submarket 2, Y% in submarket 4, Z% in submarket 7) relies on having the municipalities included in the tract data, from issue #28.

**Comment by atomtay** [comment]
![Screen Shot 2021-02-16 at 10 38 56 AM](https://user-images.githubusercontent.com/10645500/108085333-38067880-7043-11eb-9f0b-2e74cbe1f1f8.png)

Page is [up live](https://housing-submarkets.mapc.org/municipalities/) with the lattermost design, tweaked slightly. Current answers to the above questions:

 **Name for page** Municipalities (I like "Explore" but it's pretty vague, and this is very specifically a search-by-municipality page/doesn't have any more specific search functionality, like neighborhood or subregion)
**Need to decide if this is a full-page map and how it differed from the home page in layout.** Not full-page, display side-by-side with bar chart
**Only municipalities groupings?** Yes
**Tooltip to include % subregion in muni/% bar in tooltip** No, tooltip only includes count; percent displayed below
**What site copy do we want to include on this page?** Minimal copy; municipal result shows short description of each included submarket

**Comment by theryankelly** [comment]
Notes/Tasks from 2/17/2020 Meeting

- [x] Going with Municipalities for page name
- [x] Change calculation of %. Use housing units as the denominator, land area a secondary option. The third option if time does not allow is to keep as is with denominator as the number of tracts.
- [x] Need to add label to bar chart
- [x] Additional site copy with an embed of policies. **Need to decide if we are using airtable views to creating muni dependant variables.**

**Comment by theryankelly** [comment]
Interesting search issue if I search for "North" I don't get any pre-population until I start on second work "Reading". Might be true for munis with space in the name.
![image](https://user-images.githubusercontent.com/2421382/108416592-e9044300-71fc-11eb-8bbb-c5b2398aa3ed.png)
![image](https://user-images.githubusercontent.com/2421382/108416657-01745d80-71fd-11eb-8ad4-181c7d42c1f2.png)

**Comment by theryankelly** [comment]
Closing this issue as the page is up as will be for launch. Have created a new issue for the word break issue #41
